/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.pkg1;

import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Formde1 extends javax.swing.JFrame {

    /**
     * Creates new form Formde1
     */
    public Formde1() { 
        initComponents();
        setLocationRelativeTo(nu);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfHoten = new javax.swing.JTextField();
        tfDiachi = new javax.swing.JTextField();
        tfNgaySinh = new javax.swing.JTextField();
        tfmaSV = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        tfDTK = new javax.swing.JTextField();
        nam = new javax.swing.JRadioButton();
        nu = new javax.swing.JRadioButton();
        BtnAddSV = new javax.swing.JButton();
        btnSaveSV = new javax.swing.JButton();
        btnSHow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhap thong tin sinh vien");

        jLabel2.setText("Ho Ten");

        jLabel3.setText("Dia chi");

        jLabel4.setText("Ngay Sinh");

        jLabel5.setText("Gioi Tinh");

        jLabel6.setText("maSV");

        jLabel7.setText("email");

        jLabel8.setText("DTK");

        tfNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNgaySinhActionPerformed(evt);
            }
        });

        tfemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfemailActionPerformed(evt);
            }
        });

        buttonGroup1.add(nam);
        nam.setText("Nam");

        buttonGroup1.add(nu);
        nu.setText("Nu");

        BtnAddSV.setText("ThemSV");
        BtnAddSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddSVActionPerformed(evt);
            }
        });

        btnSaveSV.setText("LuuSV");
        btnSaveSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSVActionPerformed(evt);
            }
        });

        btnSHow.setText("Hiện thị");
        btnSHow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSHowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfmaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(nam)
                        .addGap(35, 35, 35)
                        .addComponent(nu)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(BtnAddSV)
                .addGap(43, 43, 43)
                .addComponent(btnSaveSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSHow)
                .addGap(24, 24, 24))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfDTK, tfDiachi, tfHoten, tfNgaySinh, tfemail, tfmaSV});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nam)
                            .addComponent(nu))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfmaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAddSV)
                    .addComponent(btnSaveSV)
                    .addComponent(btnSHow))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNgaySinhActionPerformed

    private void tfemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfemailActionPerformed

    private void BtnAddSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddSVActionPerformed
       if(KiemTraRong()==true){
           JOptionPane.showMessageDialog(null, "Ban Chua NHap du thong tin");
           return;
       }
       else{
            Student st = new Student(tfHoten.getText(),tfDiachi.getText(),tfNgaySinh.getText(),nam.isSelected()?"nam":"nu",tfmaSV.getText(),tfemail.getText(),Float.parseFloat(tfDTK.getText()));
            st.Hienthi();
            JOptionPane.showMessageDialog(null,"THem thanh cong");
       }
    }//GEN-LAST:event_BtnAddSVActionPerformed

    private void btnSaveSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSVActionPerformed
        // TODO add your handling code here:
        if(KiemTraRong()==true){
            JOptionPane.showMessageDialog(null,"Ban Chua Nhap du Thong Tin");
            return;
        }
        else{
            try {
                FileWriter fw = new FileWriter("Sinhvien.dat",true);
                BufferedWriter bw = new BufferedWriter(fw);
                Student st = new Student(tfHoten.getText(),tfDiachi.getText(),tfNgaySinh.getText(),nam.isSelected()?"nam":"nu",
                        tfmaSV.getText(),tfemail.getText(),Float.parseFloat(tfDTK.getText()));
                String $ = null;
                bw.append(st.HoTen+"$"+st.DiaChi+"$"+st.NgaySinh+"$"+st.Gioitinh+"$"+st.getMaSV()+"$"+st.getEmail()+"$"+st.getDTK());
                bw.newLine();
                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(null,"Luu Thanh cong");
            } catch (Exception e) {
               JOptionPane.showMessageDialog(null,"Luu thong tin that bai");
            }
            
        }
    }//GEN-LAST:event_btnSaveSVActionPerformed

    private void btnSHowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSHowActionPerformed
        // TODO add your handling code here:
        ArrayList StudentList = new ArrayList();
        try {
            
            FileReader fr = new FileReader("Sinhvien.dat");
            BufferedReader br = new BufferedReader(fr);
            String s = "";
            while((s=br.readLine())!=null){
                String[] a = s.split("\\$");
                Student st = new Student(a[0],a[1],a[2],a[3],a[4],a[5],Float.parseFloat(a[6]));
                StudentList.add(st);
            }
            br.close();
            fr.close();
        } catch (Exception e) {
                    System.out.println(e);
        }
        
        jfromhienthi j1 = new jfromhienthi();
        j1.setVisible(true);
        j1.setData(StudentList);
    }//GEN-LAST:event_btnSHowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formde1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formde1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formde1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formde1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formde1().setVisible(true);
            }
        });
    }
public boolean KiemTraRong(){
  if(tfHoten.getText().equals("")||tfDiachi.getText().equals("")||tfNgaySinh.getText().equals("")
          ||tfmaSV.getText().equals("")||tfemail.getText().equals("")||tfDTK.getText().equals("")||
          (!nam.isSelected() && !nu.isSelected())
                            ){
  return true;}
  return false;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddSV;
    private javax.swing.JButton btnSHow;
    private javax.swing.JButton btnSaveSV;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton nam;
    private javax.swing.JRadioButton nu;
    private javax.swing.JTextField tfDTK;
    private javax.swing.JTextField tfDiachi;
    private javax.swing.JTextField tfHoten;
    private javax.swing.JTextField tfNgaySinh;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfmaSV;
    // End of variables declaration//GEN-END:variables
}
