/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de3at13;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class jfromde3AT13 extends javax.swing.JFrame {

    /**
     * Creates new form jfromde3AT13
     */
    public jfromde3AT13() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfTenlop = new javax.swing.JTextField();
        tfSiso = new javax.swing.JTextField();
        tfHoten = new javax.swing.JTextField();
        tfMasv = new javax.swing.JTextField();
        tfDiemhocphan = new javax.swing.JTextField();
        tfDiemquatrinh = new javax.swing.JTextField();
        btnThemsv = new javax.swing.JButton();
        tfHienthi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nhap danh sach sinh vien cua lop hoc ");

        jLabel2.setText("Tenlop");

        jLabel3.setText("Siso");

        jLabel4.setText("Hoten");

        jLabel5.setText("Masv");

        jLabel6.setText("Diem hoc phan");

        jLabel7.setText("Diem qua trinh");

        btnThemsv.setText("Them sv");
        btnThemsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemsvActionPerformed(evt);
            }
        });

        tfHienthi.setText("Hienthi");
        tfHienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHienthiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThemsv)
                                .addGap(48, 48, 48)
                                .addComponent(tfHienthi))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfSiso)
                                .addComponent(tfHoten)
                                .addComponent(tfMasv)
                                .addComponent(tfDiemhocphan)
                                .addComponent(tfDiemquatrinh, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(tfTenlop, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTenlop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfMasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfDiemhocphan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfDiemquatrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemsv)
                    .addComponent(tfHienthi))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemsvActionPerformed
        // TODO add your handling code here:
        if(Kiemtrarong()==true){
            JOptionPane.showMessageDialog(null,"Ban chua nhap du vui long nhap lai");
            return;
            
        }
        else{
             try {
                FileWriter fw = new FileWriter("Lophocsv.dat",true);
                BufferedWriter bw = new BufferedWriter(fw);
                Lophoc lh = new Lophoc(Integer.parseInt(tfSiso.getText()),tfTenlop.getText());
                Sinhvien sv = new Sinhvien(tfHoten.getText(),tfMasv.getText(),Integer.parseInt(tfDiemhocphan.getText()),Integer.parseInt(tfDiemquatrinh.getText()));
                lh.hienthilp();
                sv.hienthithongtin();
                bw.append(lh.getTenlop()+"$"+lh.getSisolop()+"$"+sv.getHoten()+"$"+sv.getMasv()+"$"+sv.getDiemhocphan()+"$"+sv.getDiemquatrinh());
                bw.newLine();
                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(null,"Nhap thanh cong");
            } catch (Exception e) {
                 System.out.println(e);
                JOptionPane.showMessageDialog(null, "NHap that bai");
            }
            
             
        }
    }//GEN-LAST:event_btnThemsvActionPerformed

    private void tfHienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHienthiActionPerformed
        // TODO add your handling code here:
           if(Kiemtrarong()==true){
            JOptionPane.showMessageDialog(null,"Ban chua nhap du vui long nhap lai");
            return;
            
        }
           else{
               ArrayList DSSV = new ArrayList();
               try {
                   FileReader fr = new FileReader("Lophocsv.dat");
                   BufferedReader br = new BufferedReader(fr);
                   String s = "";
                   while((s=br.readLine())!=null){
                       String[] a = s.split("\\$");
                       Lophoc lh = new Lophoc(Integer.parseInt(a[0]),a[1]);
                       System.out.println("df");
                       Sinhvien sv = new Sinhvien(a[0],a[1],Integer.parseInt(a[2]),Integer.parseInt(a[3]));
                       DSSV.add(lh);
                       DSSV.add(sv);
                   }
                   br.close();
                   fr.close();
               } catch (Exception e) {
                   JOptionPane.showMessageDialog(null, "ko nhap dc");
                   e.printStackTrace();
               }
               for (int i = 0; i < DSSV.size(); i++) {
                 Lophoc lh=(Lophoc)DSSV.get(i);
                 Sinhvien sv =(Sinhvien)DSSV.get(i);
                 lh.hienthilp();
                 sv.hienthithongtin();
                 sv.tinhdiemTB();
                   
               }
               from31 fm = new from31();
               fm.setVisible(true);
               fm.setDaTa(DSSV);
               
           }
        
    }//GEN-LAST:event_tfHienthiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfromde3AT13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfromde3AT13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfromde3AT13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfromde3AT13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfromde3AT13().setVisible(true);
            }
        });
    }
    public boolean Kiemtrarong(){
        if(tfTenlop.getText().equals("")||tfSiso.getText().equals("")||tfHoten.getText().equals("")||tfMasv.getText().equals("")||tfDiemhocphan.getText().equals("")||tfDiemquatrinh.getText().equals("")){
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemsv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfDiemhocphan;
    private javax.swing.JTextField tfDiemquatrinh;
    private javax.swing.JButton tfHienthi;
    private javax.swing.JTextField tfHoten;
    private javax.swing.JTextField tfMasv;
    private javax.swing.JTextField tfSiso;
    private javax.swing.JTextField tfTenlop;
    // End of variables declaration//GEN-END:variables
}
