/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package De62;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;

/**
 *
 * @author cmtie
 */
public class Dictionary extends javax.swing.JFrame {

    /**
     * Creates new form Dictionary
     */
    public Dictionary() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    ArrayList<Word62> listWord = new ArrayList<>();
    public void setData(){
        Word62 w1 = new Word62(1,"one","mot");
        Word62 w2 = new Word62(2,"two","hai");
        Word62 w3 = new Word62(3,"three","ba");
        Word62 w4 = new Word62(4,"four","bon");
        Word62 w5 = new Word62(5,"five","nam");
        Word62 w6 = new Word62(6,"six","sau");
        Word62 w7 = new Word62(7,"seven","bay");
        Word62 w8 = new Word62(8,"eight","tam");
        Word62 w9 = new Word62(9,"nine","chin");
        Word62 w10 = new Word62(10,"ten","muoi");
        listWord.add(w1);
        listWord.add(w2);
        listWord.add(w3);
        listWord.add(w4);
        listWord.add(w5);
        listWord.add(w6);
        listWord.add(w7);
        listWord.add(w8);
        listWord.add(w9);
        listWord.add(w10);
        sort();
        hienthi();
    }
    
    public void hienthi(){
        for (Word62 word62 : listWord) {
            word62.Hienthi();
        }
        System.out.println("---");
    }
    public void sort(){
        Collections.sort(listWord, new Comparator<Word62>(){
            @Override
            public int compare(Word62 o1, Word62 o2) {
                return o1.getEng().compareToIgnoreCase(o2.getEng());
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfeng = new javax.swing.JTextField();
        tfvn = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("dictionary");

        jLabel2.setText("eng");

        jLabel3.setText("vn");

        tfeng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfengActionPerformed(evt);
            }
        });

        tfvn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfvnActionPerformed(evt);
            }
        });

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnadd.setText("add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfvn, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(tfeng)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnsearch)
                .addGap(44, 44, 44)
                .addComponent(btnadd)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(tfeng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfvn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnsearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnadd)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfengActionPerformed

    private void tfvnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfvnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfvnActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        if (KiemtrarongSearch() ==true) {
            JOptionPane.showMessageDialog(null,"chua nhap du thong tin");
        }
        else if(BinarySearch(tfeng.getText())==-1){
            JOptionPane.showMessageDialog(null, "ko tim thay");
            
        }
        else{
            Word62 w2 = listWord.get(BinarySearch(tfeng.getText()));
            tfvn.setText(w2.getVn());
        }
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        if(Kiemtrarong()==true){
            JOptionPane.showMessageDialog(null,"chua nhap du thong tin");
        }
        else{
            for (Word62 word62 : listWord) {
                if(tfeng.getText().equalsIgnoreCase(word62.getEng())){
                    System.out.println("tu ngay da co trong tu dien");
                    JOptionPane.showMessageDialog(null,"tu ngay da co trong tu dien");
                    return;
                }
            }
            Word62 wadd = new Word62(listWord.size()+1, tfeng.getText(), tfvn.getText());
                    listWord.add(wadd);
                    sort();
                    hienthi();
                    tfeng.setText("");
                    tfvn.setText("");
        }
    }//GEN-LAST:event_btnaddActionPerformed

    public boolean KiemtrarongSearch(){
        if (tfeng.getText().equals("")) {
           return true;
        }
        return false;
    }
    public boolean Kiemtrarong(){
        if (tfeng.getText().equals("")||tfvn.getText().equals("")) {
           return true;
        }
        return false;
    }
    public int BinarySearch(String s){
        int left = 0;
        int right = listWord.size()-1;
        int mid =0;
        while (left<=right) {
            mid = (left+right)/2;
            Word62 wmid = listWord.get(mid);
            if (wmid.getEng().equalsIgnoreCase(s)) {
                return mid;
            }
            else if(wmid.getEng().compareToIgnoreCase(s)>0){
                right = mid -1;
            }
            else{
                left = mid +1;
            }
        }
        return -1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dictionary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfeng;
    private javax.swing.JTextField tfvn;
    // End of variables declaration//GEN-END:variables
}
