/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopperson;

import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class jframesv extends javax.swing.JFrame {
    private Object nhapHovaten;
    private Object nhapDiachi;
    private Object nhapngaysinh;

    /**
     * Creates new form jframesv
     */
    public jframesv() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jthoten = new javax.swing.JTextField();
        jtdiachi = new javax.swing.JTextField();
        jtngaysinh = new javax.swing.JTextField();
        jtdiemTK = new javax.swing.JTextField();
        jtmasv = new javax.swing.JTextField();
        jtemail = new javax.swing.JTextField();
        jtsavesv = new javax.swing.JButton();
        jtaddsv = new javax.swing.JButton();
        jtgioitinh = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jthoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jthotenActionPerformed(evt);
            }
        });

        jtdiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtdiachiActionPerformed(evt);
            }
        });

        jtsavesv.setText("Lưu sv");
        jtsavesv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtsavesvActionPerformed(evt);
            }
        });

        jtaddsv.setText("THêm sv");
        jtaddsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtaddsvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(jthoten)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtdiachi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtdiemTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtmasv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtemail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtgioitinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jtsavesv)
                .addGap(29, 29, 29)
                .addComponent(jtaddsv)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtdiachi, jtdiemTK, jtemail, jthoten, jtmasv, jtngaysinh});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jtgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtdiemTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtaddsv)
                    .addComponent(jtsavesv))
                .addGap(90, 90, 90))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtdiachi, jtdiemTK, jtemail, jthoten, jtmasv, jtngaysinh});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtsavesvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtsavesvActionPerformed
        try {
            try ( // TODO add your handling code here:
            /*Student st = new Student(jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),Float.parseFloat(jTextField5.getText()),jTextField6.getText(),jTextField7.getText());
            try{
            try (FileOutputStream fos = new FileOutputStream("D:\\student.txt")) {
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(st);
            oos.close();
            }
            JOptionPane.showMessageDialog(this,"luu tru thanh cong");
            } catch (FileNotFoundException ex) {
            Logger.getLogger(jframesv.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
            }*/
                    FileOutputStream fos = new FileOutputStream("D://sinhvienat.dat"); 
                    ObjectOutputStream oos = new ObjectOutputStream(fos)) {
                Student s = new Student(jthoten.getText(),jtngaysinh.getText(), jtdiachi.getText(), jtgioitinh.getText(), jtdiemTK.getText(), jtmasv.getText(), jtemail.getText());
                
                oos.writeObject(s);
                oos.close();
                fos.close();
            }
            JOptionPane.showMessageDialog(null,"Luu file thanh cong");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"Luu file that bai");
        }
        
    }//GEN-LAST:event_jtsavesvActionPerformed

    private void jthotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jthotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jthotenActionPerformed

    private void jtdiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtdiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtdiachiActionPerformed

    private void jtaddsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtaddsvActionPerformed
        // TODO add your handling code here:
        Student s = new Student(jthoten.getText(),jtngaysinh.getText(),jtdiachi.getText(),jtgioitinh.getText(),jtdiemTK.getText(),jtmasv.getText(),jtemail.getText());
        s.xuatthongtinsinhvien();
        JOptionPane.showMessageDialog(null,"nhap thanh cong");
    }//GEN-LAST:event_jtaddsvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframesv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframesv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframesv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframesv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframesv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jtaddsv;
    private javax.swing.JTextField jtdiachi;
    private javax.swing.JTextField jtdiemTK;
    private javax.swing.JTextField jtemail;
    private javax.swing.JTextField jtgioitinh;
    private javax.swing.JTextField jthoten;
    private javax.swing.JTextField jtmasv;
    private javax.swing.JTextField jtngaysinh;
    private javax.swing.JButton jtsavesv;
    // End of variables declaration//GEN-END:variables
}
